import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '../config.js';
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const root=document.querySelector('#console');
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let state={settings:{},nav:[],pages:[],members:[],tab:'overview'};

async function isAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user)return false;const {data,error}=await supabase.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !!data&&!error}
function loginView(message=''){
  root.innerHTML=`<div class="login-wrap"><div class="login-card"><span class="console-badge">Private route</span><h1>Graphlair Console</h1><p>This page is intentionally not linked anywhere on the public website.</p><form id="login"><label class="field"><span>Email</span><input type="email" name="email" required autocomplete="username"></label><label class="field"><span>Password</span><input type="password" name="password" required autocomplete="current-password"></label><button class="btn primary full">Enter console</button><div class="error">${esc(message)}</div></form></div></div>`;
  document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const {error}=await supabase.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return loginView(error.message);if(!(await isAdmin())){await supabase.auth.signOut();return loginView('This account is not listed in admin_users.')}await refresh();};
}
async function refresh(){
  const [{data:settings},{data:nav=[]},{data:pages=[]},{data:members=[]}]=await Promise.all([
    supabase.from('site_settings').select('*').eq('id',1).maybeSingle(),
    supabase.from('navigation_items').select('*').order('sort_order'),
    supabase.from('pages').select('*').order('created_at'),
    supabase.from('team_members').select('*').order('sort_order')
  ]);
  state.settings=settings||{};state.nav=nav;state.pages=pages;state.members=members;layout();show(state.tab);
}
function layout(){
  root.innerHTML=`<div class="admin-shell"><aside class="sidebar"><div class="side-brand">GRAPH<span>LAIR</span></div><nav class="side-nav">${[['overview','Overview'],['brand','Brand'],['nav','Navigation'],['pages','Pages'],['members','Team Members'],['media','Media']].map(([k,l])=>`<button data-tab="${k}" class="${state.tab===k?'active':''}">${l}</button>`).join('')}</nav><div class="side-foot"><a class="btn ghost" href="../" target="_blank">Open public site ↗</a><button id="logout" class="btn">Sign out</button></div></aside><main class="main"><div id="panel"></div></main></div>`;
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;show(state.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===state.tab))});
  document.querySelector('#logout').onclick=async()=>{await supabase.auth.signOut();loginView()};
}
const panel=()=>document.querySelector('#panel');
async function upload(file,folder='uploads'){
  const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,'-');const path=`${folder}/${Date.now()}-${crypto.randomUUID().slice(0,8)}-${safe}`;
  const {error}=await supabase.storage.from('media').upload(path,file,{upsert:false});if(error)throw error;
  return supabase.storage.from('media').getPublicUrl(path).data.publicUrl;
}
function show(tab){
  if(tab==='overview') overview();
  if(tab==='brand') brand();
  if(tab==='nav') navigation();
  if(tab==='pages') pages();
  if(tab==='members') members();
  if(tab==='media') media();
}
function top(title,subtitle='',right=''){return `<div class="topbar"><div><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${right}</div>`}
function overview(){panel().innerHTML=`${top('Control the Lair','Public site stays clean; this console exists only at its direct URL.')}<div class="grid3"><div class="stat-card"><strong>${state.pages.length}</strong><span>PAGES</span></div><div class="stat-card"><strong>${state.members.length}</strong><span>MEMBERS</span></div><div class="stat-card"><strong>${state.nav.length}</strong><span>MENU ITEMS</span></div></div><div class="panel"><h2>Private admin URL</h2><div class="note">There is no Admin button, menu item, footer link or public reference. Keep the console URL private. The real security still comes from Supabase Auth + RLS, not from hiding the URL.</div></div>`}
function brand(){const s=state.settings;panel().innerHTML=`${top('Brand & Theme','Change the identity without touching GitHub code.')}<form id="brand-form" class="panel"><div class="grid2"><label class="field"><span>Site name</span><input name="site_name" value="${esc(s.site_name||'Graphlair')}"></label><label class="field"><span>Tagline</span><input name="tagline" value="${esc(s.tagline||'')}"></label></div><div class="grid2"><label class="field"><span>Logo URL</span><input name="logo_url" value="${esc(s.logo_url||'')}"></label><label class="field"><span>Upload / replace logo</span><input id="logo-file" type="file" accept="image/*"></label><label class="field"><span>Favicon URL</span><input name="favicon_url" value="${esc(s.favicon_url||'')}"></label><label class="field"><span>Upload / replace favicon</span><input id="favicon-file" type="file" accept="image/*"></label></div><div class="grid2">${[['primary_color','Primary / Neon',s.primary_color||'#7df46a'],['background_color','Background',s.background_color||'#050806'],['card_color','Cards',s.card_color||'#0b100d'],['text_color','Text',s.text_color||'#f7faf7'],['muted_color','Muted text',s.muted_color||'#89918c']].map(([n,l,v])=>`<label class="field"><span>${l}</span><div class="color-row"><input name="${n}" value="${esc(v)}"><input type="color" data-color-for="${n}" value="${esc(v)}"></div></label>`).join('')}</div><label class="field"><span>Footer text</span><input name="footer_text" value="${esc(s.footer_text||'')}"></label><div class="form-actions"><button class="btn primary">Save brand</button></div></form>`;
  document.querySelectorAll('[data-color-for]').forEach(c=>c.oninput=()=>document.querySelector(`[name="${c.dataset.colorFor}"]`).value=c.value);
  document.querySelector('#brand-form').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target);let logo=fd.get('logo_url'),favicon=fd.get('favicon_url');const lf=document.querySelector('#logo-file').files[0],ff=document.querySelector('#favicon-file').files[0];if(lf)logo=await upload(lf,'branding');if(ff)favicon=await upload(ff,'branding');const payload={id:1,site_name:fd.get('site_name'),tagline:fd.get('tagline'),logo_url:logo,favicon_url:favicon,primary_color:fd.get('primary_color'),background_color:fd.get('background_color'),card_color:fd.get('card_color'),text_color:fd.get('text_color'),muted_color:fd.get('muted_color'),footer_text:fd.get('footer_text')};const {error}=await supabase.from('site_settings').upsert(payload);if(error)throw error;alert('Brand updated');await refresh()}catch(x){alert(x.message)}};
}
function navigation(){panel().innerHTML=`${top('Navigation','Add, rename, hide, delete and reorder menu links.','<button id="add-nav" class="btn primary">+ Add item</button>')}<div class="panel list">${state.nav.length?state.nav.map(n=>`<form class="list-row nav-row" data-id="${n.id}"><div><input name="label" value="${esc(n.label)}"><small>Menu label</small></div><div><input name="url" value="${esc(n.url)}"><small>URL</small></div><div class="actions"><input name="sort_order" type="number" value="${n.sort_order||0}" style="width:70px"><label class="switch"><input name="is_visible" type="checkbox" ${n.is_visible?'checked':''}>Visible</label><label class="switch"><input name="is_cta" type="checkbox" ${n.is_cta?'checked':''}>CTA</label><button class="btn">Save</button><button type="button" class="btn danger" data-del="${n.id}">Delete</button></div></form>`).join(''):'<div class="empty">No navigation items.</div>'}</div>`;
  document.querySelector('#add-nav').onclick=async()=>{const {error}=await supabase.from('navigation_items').insert({label:'New link',url:'/',sort_order:99,is_visible:true});if(error)alert(error.message);else refresh()};
  document.querySelectorAll('.nav-row').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const {error}=await supabase.from('navigation_items').update({label:fd.get('label'),url:fd.get('url'),sort_order:+fd.get('sort_order'),is_visible:fd.get('is_visible')==='on',is_cta:fd.get('is_cta')==='on'}).eq('id',f.dataset.id);if(error)alert(error.message);else alert('Saved')});
  document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this menu item?')){await supabase.from('navigation_items').delete().eq('id',b.dataset.del);refresh()}})
}
function pages(){panel().innerHTML=`${top('Pages & Sections','Create any page and control every section.','<button id="add-page" class="btn primary">+ New page</button>')}<div class="panel list">${state.pages.map(p=>`<div class="list-row"><div><strong>${esc(p.title)}</strong><small>${p.is_home?'Homepage':'/'+esc(p.slug)} · ${esc(p.status)}</small></div><div></div><div class="actions"><button class="btn" data-edit-page="${p.id}">Edit</button><button class="btn primary" data-sections="${p.id}">Sections</button>${p.is_home?'':`<button class="btn danger" data-del-page="${p.id}">Delete</button>`}</div></div>`).join('')}</div>`;
  document.querySelector('#add-page').onclick=()=>pageForm();document.querySelectorAll('[data-edit-page]').forEach(b=>b.onclick=()=>pageForm(state.pages.find(x=>x.id===b.dataset.editPage)));document.querySelectorAll('[data-sections]').forEach(b=>b.onclick=()=>sectionManager(state.pages.find(x=>x.id===b.dataset.sections)));document.querySelectorAll('[data-del-page]').forEach(b=>b.onclick=async()=>{if(confirm('Delete page and all its sections?')){const {error}=await supabase.from('pages').delete().eq('id',b.dataset.delPage);if(error)alert(error.message);else refresh()}})
}
function pageForm(p={}){panel().innerHTML=`${top(p.id?'Edit page':'Create page','Routes are generated from the slug.')}<form id="page-form" class="panel"><div class="grid2"><label class="field"><span>Title</span><input name="title" required value="${esc(p.title||'')}"></label><label class="field"><span>Slug (example: about)</span><input name="slug" pattern="[a-z0-9-]*" value="${esc(p.slug||'')}"></label><label class="field"><span>Status</span><select name="status"><option ${p.status!=='draft'?'selected':''}>published</option><option ${p.status==='draft'?'selected':''}>draft</option></select></label><label class="field"><span>SEO title</span><input name="seo_title" value="${esc(p.seo_title||'')}"></label></div><label class="field"><span>SEO description</span><textarea name="seo_description">${esc(p.seo_description||'')}</textarea></label><label class="switch"><input type="checkbox" name="is_home" ${p.is_home?'checked':''}> Set as homepage</label><div class="form-actions"><button class="btn primary">Save page</button><button type="button" class="btn" id="cancel">Cancel</button></div></form>`;document.querySelector('#cancel').onclick=()=>pages();document.querySelector('#page-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const payload={title:fd.get('title'),slug:fd.get('slug').toLowerCase(),status:fd.get('status'),seo_title:fd.get('seo_title'),seo_description:fd.get('seo_description'),is_home:fd.get('is_home')==='on'};if(payload.is_home){await supabase.from('pages').update({is_home:false}).neq('id',p.id||'00000000-0000-0000-0000-000000000000')}const q=p.id?supabase.from('pages').update(payload).eq('id',p.id):supabase.from('pages').insert(payload);const {error}=await q;if(error)alert(error.message);else refresh()}}
async function sectionManager(page){const {data:secs=[]}=await supabase.from('page_sections').select('*').eq('page_id',page.id).order('sort_order');panel().innerHTML=`${top(`${page.title} sections`,'These render in order on the public page.','<button id="add-section" class="btn primary">+ Add section</button>')}<div class="panel"><div class="note">Section types: <span class="code">hero</span>, <span class="code">marquee</span>, <span class="code">manifesto</span>, <span class="code">services</span>, <span class="code">image_text</span>, <span class="code">stats</span>, <span class="code">team</span>, <span class="code">gallery</span>, <span class="code">cta</span>. Every text/image/button remains editable in the JSON content.</div></div><div class="panel list">${secs.length?secs.map(s=>`<div class="list-row"><div><strong>${esc(s.title||s.section_type)}</strong><small>${esc(s.section_type)} · order ${s.sort_order} · ${s.is_visible?'visible':'hidden'}</small></div><div></div><div class="actions"><button class="btn" data-up="${s.id}">↑</button><button class="btn" data-down="${s.id}">↓</button><button class="btn primary" data-edit-sec="${s.id}">Edit</button><button class="btn danger" data-del-sec="${s.id}">Delete</button></div></div>`).join(''):'<div class="empty">No sections yet.</div>'}</div><div class="form-actions"><button class="btn" id="back-pages">← Back to pages</button></div>`;document.querySelector('#back-pages').onclick=()=>pages();document.querySelector('#add-section').onclick=()=>sectionForm(page);document.querySelectorAll('[data-edit-sec]').forEach(b=>b.onclick=()=>sectionForm(page,secs.find(x=>x.id===b.dataset.editSec)));document.querySelectorAll('[data-del-sec]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this section?')){await supabase.from('page_sections').delete().eq('id',b.dataset.delSec);sectionManager(page)}});document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>moveSection(secs,b.dataset.up,-1,page));document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>moveSection(secs,b.dataset.down,1,page))}
async function moveSection(secs,id,dir,page){const i=secs.findIndex(s=>s.id===id),j=i+dir;if(j<0||j>=secs.length)return;const a=secs[i],b=secs[j];await Promise.all([supabase.from('page_sections').update({sort_order:b.sort_order}).eq('id',a.id),supabase.from('page_sections').update({sort_order:a.sort_order}).eq('id',b.id)]);sectionManager(page)}
function starterFor(type){const map={hero:{eyebrow:'Enter the Lair',title:'Your headline here.',description:'Short hero description.',primary_text:'Explore',primary_url:'/#services',secondary_text:'Meet the team',secondary_url:'/#team',float_title:'GRAPHLAIR',float_text:'Design × Technology'},marquee:{items:['Brand Identity','Graphic Design','Creative Tech']},manifesto:{kicker:'Point of view',title:'Make it [memorable].',text:'Your manifesto copy.'},services:{kicker:'Capabilities',description:'What you do.',items:[{title:'Brand Identity',text:'Description.'},{title:'Digital Design',text:'Description.'},{title:'Creative Tech',text:'Description.'}]},image_text:{kicker:'Story',title:'Title',text:'Description',image_url:'',button_text:'Learn more',button_url:'/'},stats:{items:[{value:'20+',title:'Projects'},{value:'10+',title:'Brands'}]},team:{kicker:'People',title:'Meet the Lair.',description:'Team cards are loaded from Members.'},gallery:{kicker:'Selected visuals',title:'Work in the wild.',images:[]},cta:{kicker:'Next move',title:'Have an idea?',text:"Let's build it.",button_text:'Start a project',button_url:'/contact'}};return map[type]||{}}
function sectionForm(page,s={}){const type=s.section_type||'hero';panel().innerHTML=`${top(s.id?'Edit section':'Add section','Change text, links, images, visibility and order.')}<form id="section-form" class="panel"><div class="grid2"><label class="field"><span>Type</span><select name="section_type">${['hero','marquee','manifesto','services','image_text','stats','team','gallery','cta'].map(t=>`<option ${type===t?'selected':''}>${t}</option>`).join('')}</select></label><label class="field"><span>Internal title</span><input name="title" value="${esc(s.title||'')}"></label><label class="field"><span>Order</span><input type="number" name="sort_order" value="${s.sort_order??0}"></label><label class="field"><span>Upload an image, then its URL is copied below</span><input id="section-file" type="file" accept="image/*"></label></div><label class="field"><span>Content (editable text / buttons / image URLs)</span><textarea class="section-json" name="content">${esc(JSON.stringify(s.content||starterFor(type),null,2))}</textarea></label><label class="switch"><input name="is_visible" type="checkbox" ${s.is_visible!==false?'checked':''}> Visible on public site</label><div class="form-actions"><button class="btn primary">Save section</button><button type="button" class="btn" id="upload-section">Upload image + copy URL</button><button type="button" class="btn" id="cancel">Cancel</button></div></form>`;
  const select=document.querySelector('[name="section_type"]');select.onchange=()=>{if(!s.id)document.querySelector('[name="content"]').value=JSON.stringify(starterFor(select.value),null,2)};document.querySelector('#cancel').onclick=()=>sectionManager(page);document.querySelector('#upload-section').onclick=async()=>{const f=document.querySelector('#section-file').files[0];if(!f)return alert('Choose an image first.');try{const url=await upload(f,'sections');await navigator.clipboard.writeText(url);alert('Uploaded. Image URL copied to clipboard:\n'+url)}catch(x){alert(x.message)}};document.querySelector('#section-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);let content;try{content=JSON.parse(fd.get('content')||'{}')}catch{return alert('Content JSON is invalid. Check commas and quotation marks.')}const payload={page_id:page.id,section_type:fd.get('section_type'),title:fd.get('title'),sort_order:+fd.get('sort_order'),content,is_visible:fd.get('is_visible')==='on'};const {error}=s.id?await supabase.from('page_sections').update(payload).eq('id',s.id):await supabase.from('page_sections').insert(payload);if(error)alert(error.message);else sectionManager(page)}}
function members(){panel().innerHTML=`${top('Team Members','This is the Team section source. Every visible member appears there automatically and gets a route such as /nafis.','<button id="add-member" class="btn primary">+ Add member</button>')}<div class="panel list">${state.members.length?state.members.map(m=>`<div class="list-row"><div style="display:flex;align-items:center;gap:12px">${m.profile_image?`<img class="preview-img" src="${esc(m.profile_image)}">`:''}<div><strong>${esc(m.name)}</strong><small>/${esc(m.slug)} · ${esc(m.role||'')}</small></div></div><div></div><div class="actions"><button class="btn primary" data-edit-member="${m.id}">Edit</button><button class="btn danger" data-del-member="${m.id}">Delete</button></div></div>`).join(''):'<div class="empty">No members yet.</div>'}</div>`;document.querySelector('#add-member').onclick=()=>memberForm();document.querySelectorAll('[data-edit-member]').forEach(b=>b.onclick=()=>memberForm(state.members.find(x=>x.id===b.dataset.editMember)));document.querySelectorAll('[data-del-member]').forEach(b=>b.onclick=async()=>{if(confirm('Delete member profile?')){await supabase.from('team_members').delete().eq('id',b.dataset.delMember);refresh()}})}
function memberForm(m={}){panel().innerHTML=`${top(m.id?'Edit member':'Add member','The slug becomes the public profile link.')}<form id="member-form" class="panel"><div class="grid2"><label class="field"><span>Name</span><input name="name" required value="${esc(m.name||'')}"></label><label class="field"><span>Slug / link</span><input name="slug" required pattern="[a-z0-9-]+" value="${esc(m.slug||'')}"></label><label class="field"><span>Role</span><input name="role" value="${esc(m.role||'')}"></label><label class="field"><span>Order</span><input name="sort_order" type="number" value="${m.sort_order||0}"></label></div><label class="field"><span>Short bio</span><textarea name="short_bio">${esc(m.short_bio||'')}</textarea></label><label class="field"><span>Full bio</span><textarea name="full_bio">${esc(m.full_bio||'')}</textarea></label><div class="grid2"><label class="field"><span>Profile image URL</span><input name="profile_image" value="${esc(m.profile_image||'')}"></label><label class="field"><span>Upload / replace photo</span><input id="member-photo" type="file" accept="image/*"></label><label class="field"><span>LinkedIn</span><input name="linkedin" value="${esc(m.linkedin||'')}"></label><label class="field"><span>GitHub</span><input name="github" value="${esc(m.github||'')}"></label><label class="field"><span>Website</span><input name="website" value="${esc(m.website||'')}"></label></div><label class="switch"><input name="is_visible" type="checkbox" ${m.is_visible!==false?'checked':''}> Visible</label><div class="form-actions"><button class="btn primary">Save member</button><button type="button" class="btn" id="cancel">Cancel</button></div></form>`;document.querySelector('#cancel').onclick=()=>members();document.querySelector('#member-form').onsubmit=async e=>{e.preventDefault();try{const fd=new FormData(e.target);let img=fd.get('profile_image');const file=document.querySelector('#member-photo').files[0];if(file)img=await upload(file,'members');const payload={name:fd.get('name'),slug:fd.get('slug').toLowerCase(),role:fd.get('role'),sort_order:+fd.get('sort_order'),short_bio:fd.get('short_bio'),full_bio:fd.get('full_bio'),profile_image:img,linkedin:fd.get('linkedin'),github:fd.get('github'),website:fd.get('website'),is_visible:fd.get('is_visible')==='on'};const {error}=m.id?await supabase.from('team_members').update(payload).eq('id',m.id):await supabase.from('team_members').insert(payload);if(error)throw error;alert('Member saved. Visible members are automatically shown in the Team section.');await refresh()}catch(x){alert(x.message)}}}
async function media(){const {data:items=[],error}=await supabase.storage.from('media').list('',{limit:100});let all=[];if(!error){for(const folder of ['branding','members','sections','uploads']){const {data=[]}=await supabase.storage.from('media').list(folder,{limit:100});all.push(...data.filter(x=>x.name).map(x=>({name:x.name,path:`${folder}/${x.name}`})))}}panel().innerHTML=`${top('Media Library','Upload or delete assets stored in Supabase.','<label class="btn primary">+ Upload<input id="media-upload" type="file" accept="image/*" hidden></label>')}<div class="panel"><div class="media-grid">${all.length?all.map(x=>{const url=supabase.storage.from('media').getPublicUrl(x.path).data.publicUrl;return `<div class="media-item"><img src="${esc(url)}" alt=""><button data-delete-media="${esc(x.path)}">×</button><div class="media-meta" title="${esc(url)}" data-copy="${esc(url)}">${esc(x.name)}</div></div>`}).join(''):'<div class="empty" style="grid-column:1/-1">No media uploaded yet.</div>'}</div></div><div class="note">Click a filename to copy its public URL. Deleting an asset does not automatically remove references to it from sections or member profiles.</div>`;document.querySelector('#media-upload').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await upload(f,'uploads');media()}catch(x){alert(x.message)}};document.querySelectorAll('[data-copy]').forEach(x=>x.onclick=async()=>{await navigator.clipboard.writeText(x.dataset.copy);alert('URL copied')});document.querySelectorAll('[data-delete-media]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this file permanently?')){const {error}=await supabase.storage.from('media').remove([b.dataset.deleteMedia]);if(error)alert(error.message);else media()}})}

const {data:{session}}=await supabase.auth.getSession();if(!session)loginView();else if(await isAdmin())await refresh();else{await supabase.auth.signOut();loginView('Signed-in account is not an admin.')}
